# CPM Package Lock
# This file should be committed to version control

# fmt
CPMDeclarePackage(fmt
  GIT_TAG 11.0.2
  GITHUB_REPOSITORY fmtlib/fmt
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# magic_enum
CPMDeclarePackage(magic_enum
  VERSION 0.9.6
  GITHUB_REPOSITORY Neargye/magic_enum
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# glaze
CPMDeclarePackage(glaze
  VERSION 3.3.1
  GITHUB_REPOSITORY stephenberry/glaze
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# zlib
CPMDeclarePackage(zlib
  NAME zlib
  GIT_TAG 2.2.1
  GITHUB_REPOSITORY zlib-ng/zlib-ng
  OPTIONS
    "ZLIB_COMPAT ON"
    "ZLIB_BUILD_EXAMPLES OFF"
    "ZLIB_ENABLE_TESTS OFF"
    "POSITION_INDEPENDENT_CODE ON"
    "WITH_GTEST OFF"
  USE_CACHE OFF
)
# Catch2
CPMDeclarePackage(Catch2
  NAME Catch2
  VERSION 3.7.0
  GITHUB_REPOSITORY catchorg/Catch2
  OPTIONS
    "CATCH_INSTALL_DOCS OFF"
    "CATCH_CONFIG_FAST_COMPILE ON"
    "CATCH_INSTALL_EXTRAS ON"
)
# qhull
CPMDeclarePackage(qhull
  NAME qhull
  GIT_TAG 2020.2
  DOWNLOAD_ONLY ON
  GITHUB_REPOSITORY qhull/qhull
)
# thread-pool
CPMDeclarePackage(thread-pool
  VERSION 4.1.0
  GITHUB_REPOSITORY bshoshany/thread-pool
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# cpptrace
CPMDeclarePackage(cpptrace
  VERSION 0.7.0
  GITHUB_REPOSITORY jeremy-rifkin/cpptrace
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# glfw
CPMDeclarePackage(glfw
  NAME glfw
  GIT_TAG 3.4
  GITHUB_REPOSITORY glfw/glfw
  OPTIONS
    "GLFW_BUILD_DOCS OFF"
    "GLFW_BUILD_EXAMPLES OFF"
    "GLFW_BUILD_TESTS OFF"
    "GLFW_INSTALL OFF"
    "GLFW_USE_OSMESA OFF"
    "GLFW_VULKAN_STATIC OFF"
    "USE_MSVC_RUNTIME_LIBRARY_DLL OFF"
)
# DiligentCore (unversioned)
# CPMDeclarePackage(DiligentCore
#  NAME DiligentCore
#  GIT_TAG master
#  GITHUB_REPOSITORY DiligentGraphics/DiligentCore
#  OPTIONS
#    "DILIGENT_NO_RENDER_STATE_PACKAGER ON"
#    "DILIGENT_NO_FORMAT_VALIDATION ON"
#    "DILIGENT_NO_OPENGL ON"
#    "DILIGENT_NO_VULKAN OFF"
#    "DILIGENT_NO_DIRECT3D11 ON"
#    "DILIGENT_NO_DIRECT3D12 OFF"
#    "DILIGENT_BUILD_TESTS OFF"
#  PATCH_COMMAND git restore Graphics/HLSL2GLSLConverterLib/src/HLSL2GLSLConverterImpl.cpp COMMAND git restore Graphics/GraphicsEngineVulkan/src/VulkanUtilities/VulkanInstance.cpp
#)
# utfcpp
CPMDeclarePackage(utfcpp
  VERSION 4.0.5
  GITHUB_REPOSITORY nemtrif/utfcpp
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# lunasvg
CPMDeclarePackage(lunasvg
  VERSION 2.4.0
  GITHUB_REPOSITORY sammycage/lunasvg
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
# libwebp
CPMDeclarePackage(libwebp
  NAME libwebp
  VERSION 1.4.0
  GITHUB_REPOSITORY webmproject/libwebp
  OPTIONS
    "BUILD_SHARED_LIBS OFF"
    "WEBP_BUILD_ANIM_UTILS OFF"
    "WEBP_BUILD_CWEBP OFF"
    "WEBP_BUILD_DWEBP OFF"
    "WEBP_BUILD_GIF2WEBP OFF"
    "WEBP_BUILD_IMG2WEBP OFF"
    "WEBP_BUILD_VWEBP OFF"
    "WEBP_BUILD_WEBPINFO OFF"
    "WEBP_BUILD_WEBPMUX OFF"
    "WEBP_BUILD_LIBWEBPMUX ON"
    "WEBP_BUILD_LIBWEBPMUX ON"
    "WEBP_USE_THREAD ON"
    "WEBP_NEAR_LOSSLESS ON"
    "WEBP_LINK_STATIC ON"
    "WEBP_BUILD_EXTRAS OFF"
)
# LuaBridge3 (unversioned)
# CPMDeclarePackage(LuaBridge3
#  NAME LuaBridge3
#  GIT_TAG master
#  GITHUB_REPOSITORY kunitoki/LuaBridge3
#  OPTIONS
#    "LUABRIDGE_TESTING OFF"
#    "LUABRIDGE_COVERAGE OFF"
#)
# luau
CPMDeclarePackage(luau
  NAME luau
  GIT_TAG 0.640
  GITHUB_REPOSITORY luau-lang/luau
  OPTIONS
    "LUAU_BUILD_CLI OFF"
    "LUAU_BUILD_TESTS OFF"
    "LUAU_BUILD_BENCHMARKS OFF"
    "LUAU_BUILD_WEB OFF"
)
# libcpr
CPMDeclarePackage(libcpr
  NAME libcpr
  GIT_TAG 1.10.5
  GITHUB_REPOSITORY libcpr/cpr
  OPTIONS
    "BUILD_SHARED_LIBS OFF"
    "CPR_ENABLE_CURL_HTTP_ONLY ON"
    "CPR_ENABLE_SSL ON"
    "CURL_ZLIB ON"
  PATCHES libcpr.patch
)
# libwebm (unversioned)
# CPMDeclarePackage(libwebm
#  NAME libwebm
#  GIT_TAG libwebm-1.0.0.31
#  GITHUB_REPOSITORY webmproject/libwebm
#  OPTIONS
#    "BUILD_SHARED_LIBS OFF"
#    "ENABLE_WEBMTS OFF"
#    "ENABLE_WEBMINFO OFF"
#    "ENABLE_WEBM_PARSER OFF"
#    "ENABLE_TESTS OFF"
#    "ENABLE_SAMPLE_PROGRAMS OFF"
#)
# assimp
CPMDeclarePackage(assimp
  NAME assimp
  GIT_TAG 4.1.0
  GITHUB_REPOSITORY edunad/assimp
  OPTIONS
    "BUILD_SHARED_LIBS OFF"
    "ASSIMP_NO_EXPORT ON"
    "ASSIMP_BUILD_ZLIB OFF"
    "ASSIMP_BUILD_ASSIMP_TOOLS OFF"
    "ASSIMP_BUILD_TESTS OFF"
    "ASSIMP_BUILD_SAMPLES OFF"
    "ASSIMP_BUILD_DOCS OFF"
    "ASSIMP_BUILD_ASSIMP_VIEW OFF"
    "USE_STATIC_CRT ON"
    "ASSIMP_WARNINGS_AS_ERRORS OFF"
    "ASSIMP_INSTALL OFF"
    "ASSIMP_INSTALL_PDB OFF"
    "ASSIMP_BUILD_DRACO ON"
    "ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF"
    "ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF"
    "ASSIMP_BUILD_OBJ_IMPORTER ON"
    "ASSIMP_BUILD_FBX_IMPORTER ON"
    "ASSIMP_BUILD_DAE_IMPORTER ON"
    "ASSIMP_BUILD_STL_IMPORTER ON"
    "ASSIMP_BUILD_GLTF_IMPORTER ON"
    "ASSIMP_BUILD_3DS_IMPORTER ON"
    "ASSIMP_BUILD_MD5_IMPORTER ON"
)
# clip
CPMDeclarePackage(clip
  NAME clip
  VERSION 1.9
  GITHUB_REPOSITORY dacap/clip
  OPTIONS
    "CLIP_EXAMPLES OFF"
    "CLIP_ENABLE_IMAGE OFF"
    "CLIP_TESTS OFF"
)
# muli (unversioned)
# CPMDeclarePackage(muli
#  NAME muli
#  GIT_TAG c7697eaee46d128b967368d7454aa2459fed15d4
#  GITHUB_REPOSITORY Sopiro/Muli
#  OPTIONS
#    "MULI_BUILD_DEMO OFF"
#)
# imgui
CPMDeclarePackage(imgui
  NAME imgui
  VERSION 1.91.0
  GIT_TAG docking
  DOWNLOAD_ONLY YES
  GITHUB_REPOSITORY ocornut/imgui
)
# Jolt
CPMDeclarePackage(Jolt
  NAME Jolt
  VERSION 5.1.0
  GITHUB_REPOSITORY jrouwe/JoltPhysics
  SOURCE_SUBDIR Build
  OPTIONS
    "INTERPROCEDURAL_OPTIMIZATION ON"
    "COMPILE_AS_SHARED_LIBRARY OFF"
    "USE_STATIC_MSVC_RUNTIME_LIBRARY ON"
    "ENABLE_ALL_WARNINGS OFF"
    "DEBUG_RENDERER_IN_DISTRIBUTION OFF"
    "PROFILER_IN_DISTRIBUTION OFF"
    "PROFILER_IN_DEBUG_AND_RELEASE OFF"
)
