#ifndef DEFS_SH_HEADER_GUARD
#define DEFS_SH_HEADER_GUARD

// SAMPLES ENUM -------
#define SAMPLE_MAT_ALBEDO 0
#define SAMPLE_MAT_NORMAL 1
#define SAMPLE_MAT_SPECULAR 2
#define SAMPLE_MAT_EMISSION 3
#define SAMPLE_MAT_DISPLACEMENT 4

#define DEFERRED_DIFFUSE 0
#define DEFERRED_NORMAL 1
#define DEFERRED_EMISSION_SPEC 2
#define DEFERRED_BITMASK 3
#define DEFERRED_DEPTH 4

#define SAMPLE_INSTANCE_DATA 5
#define SAMPLE_LIGHTS 6

// LIGHT ENUM -------
#define LIGHT_POINT 0
#define LIGHT_SPOT 1

#endif // DEFS_SH_HEADER_GUARD
