#ifndef DEFS_SH_HEADER_GUARD
#define DEFS_SH_HEADER_GUARD

// SAMPLES ENUM -------
#define SAMPLE_MAT_ALBEDO 0
#define SAMPLE_MAT_NORMAL 1
#define SAMPLE_MAT_SPECULAR 2
#define SAMPLE_MAT_EMISSION 3
#define SAMPLE_MAT_OPACITY 4
#define SAMPLE_MAT_DISPLACEMENT 5

#define SAMPLE_LIGHTS 6

#define SAMPLE_DEPTH 7

#define SAMPLE_CLUSTERS 8
#define SAMPLE_LIGHTINDICES 9
#define SAMPLE_LIGHTGRID 10
#define SAMPLE_ATOMIC_INDEX 11

#define SAMPLE_INSTANCE_DATA 12

// LIGHT ENUM -------
#define LIGHT_POINT 0
#define LIGHT_SPOT 1

#endif // DEFS_SH_HEADER_GUARD
