#ifndef DEFS_SH_HEADER_GUARD
#define DEFS_SH_HEADER_GUARD

// SAMPLES ENUM -------
#define SAMPLE_MAT_ALBEDO 0
#define SAMPLE_MAT_NORMAL 1
#define SAMPLE_MAT_SPECULAR 2
#define SAMPLE_MAT_EMISSION 3
#define SAMPLE_MAT_DISPLACEMENT 4

#define SAMPLE_LIGHTS 5

#define SAMPLE_DEPTH 6
#define SAMPLE_MASK 7

#define SAMPLE_CLUSTERS 0
#define SAMPLE_ATOMIC_INDEX 1

#define SAMPLE_LIGHTINDICES 8
#define SAMPLE_LIGHTGRID 9

#define SAMPLE_INSTANCE_DATA 10

// LIGHT ENUM -------
#define LIGHT_POINT 0
#define LIGHT_SPOT 1

#endif // DEFS_SH_HEADER_GUARD
