name: CI/CD - BUILD

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: master

permissions:
  contents: write
  actions: write
  checks: write
  pull-requests: write
  discussions: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: rawrbox
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget cmake libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols libvulkan-dev libssl-dev libvpx-dev gcc-14 g++-14 libgl1-mesa-dev libglew-dev ninja-build python3-pip libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev uuid-dev libxcb-util-dev

      - name: Cache c++
        uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5
        with:
          append-timestamp: false
          restore-keys: host-${{ runner.os }}-${{ hashFiles('./CMakeLists.txt', './rawrbox.gltf/CMakeLists.txt', './rawrbox.bass/CMakeLists.txt', './rawrbox.engine/CMakeLists.txt', './rawrbox.math/CMakeLists.txt', './rawrbox.network/CMakeLists.txt', './rawrbox.physics_2d/CMakeLists.txt', './rawrbox.physics_3d/CMakeLists.txt', './rawrbox.render/CMakeLists.txt', './rawrbox.resources/CMakeLists.txt', './rawrbox.scripting/CMakeLists.txt', './rawrbox.ui/CMakeLists.txt', './rawrbox.utils/CMakeLists.txt', './rawrbox.webm/CMakeLists.txt', './rawrbox.steamworks/CMakeLists.txt', './rawrbox.imgui/CMakeLists.txt') }}-
          key: host-${{ runner.os }}-${{ hashFiles('./CMakeLists.txt', './rawrbox.gltf/CMakeLists.txt', './rawrbox.bass/CMakeLists.txt', './rawrbox.engine/CMakeLists.txt', './rawrbox.math/CMakeLists.txt', './rawrbox.network/CMakeLists.txt', './rawrbox.physics_2d/CMakeLists.txt', './rawrbox.physics_3d/CMakeLists.txt', './rawrbox.render/CMakeLists.txt', './rawrbox.resources/CMakeLists.txt', './rawrbox.scripting/CMakeLists.txt', './rawrbox.ui/CMakeLists.txt', './rawrbox.utils/CMakeLists.txt', './rawrbox.webm/CMakeLists.txt', './rawrbox.steamworks/CMakeLists.txt', './rawrbox.imgui/CMakeLists.txt') }}

      - name: CMAKE Setup
        id: setup
        run: |
          mkdir -p build && cd build
          CC=gcc-14 CXX=g++-14 cmake .. -G Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_EXPORT_COMPILE_COMMANDS="ON" -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DRAWRBOX_DEV_MODE:BOOL="ON"
          cd ../

      - name: Build
        id: build
        run: cd build && ninja

      - name: Run tests
        if: contains(github.event.pull_request.labels.*.name, '⚠️ SKIP_TESTS ⚠️') != true
        run: |
          cd build
          ctest --test-dir ./rawrbox.math --output-on-failure
          ctest --test-dir ./rawrbox.utils --output-on-failure
          ctest --test-dir ./rawrbox.render --output-on-failure
          ctest --test-dir ./rawrbox.engine --output-on-failure
          ctest --test-dir ./rawrbox.resources --output-on-failure
          ctest --test-dir ./rawrbox.scripting --output-on-failure
          ctest --test-dir ./rawrbox.network --output-on-failure

      - name: Upload build artifacts
        if: github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, '⚠️ UPLOAD ⚠️')
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: output
          path: bin

      - name: Release
        if: github.ref == 'refs/heads/master' && github.repository_owner == 'edunad'
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
