name: CI/CD - CHECKS

on:
  pull_request_target:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
  comment:
    needs: label
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, '📜 SCRIPTING')
    steps:
      - name: Find comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: ## NOTICE  - A LUA API change was detected ⚠

      - name: Create / Update comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > [!IMPORTANT]
            > A LUA API change was detected ⚠ <br> Ensure [**wiki** / **rawrbox-lib**](https://github.com/edunad/rawrbox-wiki) is up to date.
          edit-mode: replace
